COMPONENT=test_sched_inv.o
INTERFACES=
DEPENDENCIES= crt sched capmgr channel
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api #required for cos_sinv in llboot.h!

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
