C_OBJS=exe_self_suspended.o
ASM_OBJS=
COMPONENT=exe_ss.o
INTERFACES=exe_self_suspension
DEPENDENCIES=cbuf_c sched sched_conf printc mem_mgr_large valloc lock timed_blk
IF_LIB=

include ../../Makefile.subsubdir

