C_OBJS=robot_sched.o
ASM_OBJS=
COMPONENT=robot_scheduler.o
INTERFACES=robot_sched
DEPENDENCIES=robot_cont sched mem_mgr_large mem_mgr jpeg valloc
IF_LIB=
ADDITIONAL_LIBS= -lcobj_format -lcos_kernel_api -lcos_defkernel_api -lsl -lheap -lsl_thd_static_backend -lsl_lock -lsl_mod_fprr

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
