C_OBJS=robot_sched.o
ASM_OBJS=
COMPONENT=robot_scheduler.o
INTERFACES=robot_sched
DEPENDENCIES=capmgr sched
IF_LIB=
ADDITIONAL_LIBS= -lcobj_format -lcos_kernel_api -lcos_defkernel_api 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
