C_OBJS=stkmgr.o
ASM_OBJS=
COMPONENT=smn.o
INTERFACES=stkmgr
DEPENDENCIES=mem_mgr_large printc sched cinfo valloc mem_pool
IF_LIB=../complib.o

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
