C_OBJS=robot_cont.o
ASM_OBJS=
COMPONENT=robot_controller.o
INTERFACES=robot_cont
DEPENDENCIES=capmgr sched netbsd camera
IF_LIB=
ADDITIONAL_LIBS= -lcos_kernel_api -lcobj_format -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
