C_OBJS=malloc_comp.o
ASM_OBJS=
COMPONENT=malloccomp.o
INTERFACES=test_malloc_comp
DEPENDENCIES=printc quarantine qfault cbuf_mgr valloc voter 
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
