C_OBJS=cbuf.o cbufp.o
ASM_OBJS=
COMPONENT=buf.o
INTERFACES=cbuf_c
DEPENDENCIES=sched printc lock mem_mgr_large valloc cinfo mem_pool cbufp

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
