C_OBJS=backup_driver.o
ASM_OBJS=
COMPONENT=backup_driver_comp.o
INTERFACES=
DEPENDENCIES=capmgr sched robot_cont
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
