COMPONENT=microipi.o
INTERFACES=
DEPENDENCIES=capmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLCAPMGR) -lsl_thd_static_backend -lsl_mod_fprr

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
