/**
 * Copyright 2011 by Qi Wang, interwq@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */


#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub_spdid(mempool_tmem_mgr_event_waiting)
cos_asm_server_stub_spdid(mempool_put_mem)
cos_asm_server_stub_spdid(mempool_get_mem)
cos_asm_server_stub_spdid(mempool_clear_glb_blked)
cos_asm_server_stub_spdid(mempool_set_mgr_desired)
