/**
 * Copyright 2011 by Gabriel Parmer, gparmer@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>

.text
cos_asm_server_stub(luakv_getstring_bytable)
cos_asm_server_stub(luakv_getstring)
cos_asm_server_stub(luakv_putstring_bytable)
cos_asm_server_stub(luakv_putstring)
cos_asm_server_stub(luakv_getnumber_bytable)
cos_asm_server_stub(luakv_getnumber)
cos_asm_server_stub(luakv_putnumber_bytable)
cos_asm_server_stub(luakv_putnumber)
