C_OBJS=booter.o
ASM_OBJS=
COMPONENT=boot.o
INTERFACES=cinfo failure_notif
DEPENDENCIES=sched printc mem_mgr sched_conf cgraph
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
