C_OBJS=ninf.o util.o
ASM_OBJS=
COMPONENT=network_interface_nf.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
OBJLIBS+= $(POSIX_LIB)
ADDITIONAL_LIBS=-lcobj_format -lcos_defkernel_api -lcos_kernel_api -lsl -lheap -lsl_mod_fprr -lsl_thd_static_backend -lcos_defkernel_api -ldpdk

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
