/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub(call)
cos_asm_server_stub(call_two)
cos_asm_server_stub(call_three)
cos_asm_server_stub(call_four)

cos_asm_server_stub(call_arg)
cos_asm_server_stub(call_args)

cos_asm_server_stub_rets(call_3rets)
