/**
 * Redistribution of this file is permitted under the BSD two clause license.
 *
 * Copyright 2020, The George Washington University
 * Author: Gabe Parmer gparmer@gwu.edu
 */

#include <cos_asm_stubs.h>

cos_asm_stub(pong_call)
cos_asm_stub(pong_ret)
cos_asm_stub(pong_arg)
cos_asm_stub(pong_args)
cos_asm_stub(pong_send)

cos_asm_stub_indirect(pong_wideargs)
cos_asm_stub_indirect(pong_argsrets)
cos_asm_stub_indirect(pong_widerets)
cos_asm_stub_indirect(pong_subset)
cos_asm_stub_indirect(pong_ids)
