/**
 * Copyright 2010 by The George Washington University.  All rights reserved.
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 *
 * Author: Gabriel Parmer, gparmer@gwu.edu, 2010
 */

#include <cos_asm_server_stub_simple_stack.h>

.text	

cos_asm_server_stub_spdid(vas_mgr_expand)
cos_asm_server_stub_spdid(vas_mgr_contract)
cos_asm_server_stub_spdid(vas_mgr_take)
