INCLUDE_INCDIR=./include
BACKWARD_INCDIR=./include/backward
BITS_INCDIR=./include/bits
DEBUG_INCDIR=./include/debug
EXT_INCDIR=./include/ext

INCLUDE_SYMS=./libstdc++-headers/bits/unwind-pe.h \
./libstdc++-v3-4.8/include/c_global/cassert \
./libstdc++-v3-4.8/include/c_global/cctype \
./libstdc++-v3-4.8/include/c_global/cerrno \
./libstdc++-v3-4.8/include/c_global/cfloat \
./libstdc++-v3-4.8/include/c_global/climits \
./libstdc++-v3-4.8/include/c_global/clocale \
./libstdc++-v3-4.8/include/c_global/cmath \
./libstdc++-v3-4.8/include/c_global/cstdarg \
./libstdc++-v3-4.8/include/c_global/cstddef \
./libstdc++-v3-4.8/include/c_global/cstdint \
./libstdc++-v3-4.8/include/c_global/cstdio \
./libstdc++-v3-4.8/include/c_global/cstdlib \
./libstdc++-v3-4.8/include/c_global/cstring \
./libstdc++-v3-4.8/include/c_global/ctime \
./libstdc++-v3-4.8/include/c_global/cwchar \
./libstdc++-v3-4.8/include/c_global/cwctype \
./libstdc++-v3-4.8/include/std/algorithm \
./libstdc++-v3-4.8/include/std/array \
./libstdc++-v3-4.8/include/std/atomic \
./libstdc++-v3-4.8/include/std/bitset \
./libstdc++-v3-4.8/include/std/chrono \
./libstdc++-v3-4.8/include/std/complex \
./libstdc++-v3-4.8/include/std/condition_variable \
./libstdc++-v3-4.8/include/std/deque \
./libstdc++-v3-4.8/include/std/fstream \
./libstdc++-v3-4.8/include/std/functional \
./libstdc++-v3-4.8/include/std/future \
./libstdc++-v3-4.8/include/std/iomanip \
./libstdc++-v3-4.8/include/std/ios \
./libstdc++-v3-4.8/include/std/iosfwd \
./libstdc++-v3-4.8/include/std/iostream \
./libstdc++-v3-4.8/include/std/istream \
./libstdc++-v3-4.8/include/std/iterator \
./libstdc++-v3-4.8/include/std/limits \
./libstdc++-v3-4.8/include/std/list \
./libstdc++-v3-4.8/include/std/locale \
./libstdc++-v3-4.8/include/std/map \
./libstdc++-v3-4.8/include/std/memory \
./libstdc++-v3-4.8/include/std/mutex \
./libstdc++-v3-4.8/include/std/numeric \
./libstdc++-v3-4.8/include/std/ostream \
./libstdc++-v3-4.8/include/std/queue \
./libstdc++-v3-4.8/include/std/random \
./libstdc++-v3-4.8/include/std/ratio \
./libstdc++-v3-4.8/include/std/regex \
./libstdc++-v3-4.8/include/std/set \
./libstdc++-v3-4.8/include/std/sstream \
./libstdc++-v3-4.8/include/std/stack \
./libstdc++-v3-4.8/include/std/stdexcept \
./libstdc++-v3-4.8/include/std/streambuf \
./libstdc++-v3-4.8/include/std/string \
./libstdc++-v3-4.8/include/std/system_error \
./libstdc++-v3-4.8/include/std/thread \
./libstdc++-v3-4.8/include/std/tuple \
./libstdc++-v3-4.8/include/std/type_traits \
./libstdc++-v3-4.8/include/std/utility \
./libstdc++-v3-4.8/include/std/vector \
./libstdc++-v3-4.8/libsupc++/cxxabi.h \
./libstdc++-v3-4.8/libsupc++/exception \
./libstdc++-v3-4.8/libsupc++/initializer_list \
./libstdc++-v3-4.8/libsupc++/new \
./libstdc++-v3-4.8/libsupc++/typeinfo

BACKWARD_SYMS=./libstdc++-v3-4.8/include/backward/auto_ptr.h \
./libstdc++-v3-4.8/include/backward/binders.h \

BITS_SYMS=./libstdc++-headers/bits/c++config.h \
./libstdc++-headers/bits/gthr-default.h \
./libstdc++-headers/bits/gthr.h \
./libstdc++-headers/bits/gthr-single.h \
./libstdc++-headers/bits/os_defines.h \
./libstdc++-v3-4.8/config/allocator/new_allocator_base.h \
./libstdc++-v3-4.8/config/cpu/generic/atomic_word.h \
./libstdc++-v3-4.8/config/cpu/generic/cpu_defines.h \
./libstdc++-v3-4.8/config/cpu/generic/cxxabi_tweaks.h \
./libstdc++-v3-4.8/config/cpu/generic/opt/bits/opt_random.h \
./libstdc++-v3-4.8/config/io/basic_file_stdio.h \
./libstdc++-v3-4.8/config/io/c_io_stdio.h \
./libstdc++-v3-4.8/config/locale/generic/c_locale.h \
./libstdc++-v3-4.8/config/locale/generic/messages_members.h \
./libstdc++-v3-4.8/config/locale/generic/time_members.h \
./libstdc++-v3-4.8/config/os/generic/ctype_base.h \
./libstdc++-v3-4.8/config/os/generic/ctype_inline.h \
./libstdc++-v3-4.8/config/os/generic/error_constants.h \
./libstdc++-v3-4.8/include/bits/algorithmfwd.h \
./libstdc++-v3-4.8/include/bits/allocator.h \
./libstdc++-v3-4.8/include/bits/alloc_traits.h \
./libstdc++-v3-4.8/include/bits/atomic_base.h \
./libstdc++-v3-4.8/include/bits/basic_ios.h \
./libstdc++-v3-4.8/include/bits/basic_ios.tcc \
./libstdc++-v3-4.8/include/bits/basic_string.h \
./libstdc++-v3-4.8/include/bits/basic_string.tcc \
./libstdc++-v3-4.8/include/bits/c++0x_warning.h \
./libstdc++-v3-4.8/include/bits/char_traits.h \
./libstdc++-v3-4.8/include/bits/codecvt.h \
./libstdc++-v3-4.8/include/bits/concept_check.h \
./libstdc++-v3-4.8/include/bits/cpp_type_traits.h \
./libstdc++-v3-4.8/include/bits/deque.tcc \
./libstdc++-v3-4.8/include/bits/fstream.tcc \
./libstdc++-v3-4.8/include/bits/functexcept.h \
./libstdc++-v3-4.8/include/bits/functional_hash.h \
./libstdc++-v3-4.8/include/bits/ios_base.h \
./libstdc++-v3-4.8/include/bits/istream.tcc \
./libstdc++-v3-4.8/include/bits/list.tcc \
./libstdc++-v3-4.8/include/bits/locale_classes.h \
./libstdc++-v3-4.8/include/bits/locale_classes.tcc \
./libstdc++-v3-4.8/include/bits/locale_facets.h \
./libstdc++-v3-4.8/include/bits/locale_facets_nonio.h \
./libstdc++-v3-4.8/include/bits/locale_facets_nonio.tcc \
./libstdc++-v3-4.8/include/bits/locale_facets.tcc \
./libstdc++-v3-4.8/include/bits/localefwd.h \
./libstdc++-v3-4.8/include/bits/memoryfwd.h \
./libstdc++-v3-4.8/include/bits/move.h \
./libstdc++-v3-4.8/include/bits/ostream_insert.h \
./libstdc++-v3-4.8/include/bits/ostream.tcc \
./libstdc++-v3-4.8/include/bits/postypes.h \
./libstdc++-v3-4.8/include/bits/ptr_traits.h \
./libstdc++-v3-4.8/include/bits/random.h \
./libstdc++-v3-4.8/include/bits/random.tcc \
./libstdc++-v3-4.8/include/bits/range_access.h \
./libstdc++-v3-4.8/include/bits/regex_compiler.h \
./libstdc++-v3-4.8/include/bits/regex_constants.h \
./libstdc++-v3-4.8/include/bits/regex_cursor.h \
./libstdc++-v3-4.8/include/bits/regex_error.h \
./libstdc++-v3-4.8/include/bits/regex_grep_matcher.h \
./libstdc++-v3-4.8/include/bits/regex_grep_matcher.tcc \
./libstdc++-v3-4.8/include/bits/regex.h \
./libstdc++-v3-4.8/include/bits/regex_nfa.h \
./libstdc++-v3-4.8/include/bits/regex_nfa.tcc \
./libstdc++-v3-4.8/include/bits/shared_ptr_base.h \
./libstdc++-v3-4.8/include/bits/shared_ptr.h \
./libstdc++-v3-4.8/include/bits/sstream.tcc \
./libstdc++-v3-4.8/include/bits/stl_algobase.h \
./libstdc++-v3-4.8/include/bits/stl_algo.h \
./libstdc++-v3-4.8/include/bits/stl_bvector.h \
./libstdc++-v3-4.8/include/bits/stl_construct.h \
./libstdc++-v3-4.8/include/bits/stl_deque.h \
./libstdc++-v3-4.8/include/bits/stl_function.h \
./libstdc++-v3-4.8/include/bits/stl_heap.h \
./libstdc++-v3-4.8/include/bits/stl_iterator_base_funcs.h \
./libstdc++-v3-4.8/include/bits/stl_iterator_base_types.h \
./libstdc++-v3-4.8/include/bits/stl_iterator.h \
./libstdc++-v3-4.8/include/bits/stl_list.h \
./libstdc++-v3-4.8/include/bits/stl_map.h \
./libstdc++-v3-4.8/include/bits/stl_multimap.h \
./libstdc++-v3-4.8/include/bits/stl_multiset.h \
./libstdc++-v3-4.8/include/bits/stl_numeric.h \
./libstdc++-v3-4.8/include/bits/stl_pair.h \
./libstdc++-v3-4.8/include/bits/stl_queue.h \
./libstdc++-v3-4.8/include/bits/stl_raw_storage_iter.h \
./libstdc++-v3-4.8/include/bits/stl_relops.h \
./libstdc++-v3-4.8/include/bits/stl_set.h \
./libstdc++-v3-4.8/include/bits/stl_stack.h \
./libstdc++-v3-4.8/include/bits/stl_tempbuf.h \
./libstdc++-v3-4.8/include/bits/stl_tree.h \
./libstdc++-v3-4.8/include/bits/stl_uninitialized.h \
./libstdc++-v3-4.8/include/bits/stl_vector.h \
./libstdc++-v3-4.8/include/bits/streambuf_iterator.h \
./libstdc++-v3-4.8/include/bits/streambuf.tcc \
./libstdc++-v3-4.8/include/bits/stream_iterator.h \
./libstdc++-v3-4.8/include/bits/stringfwd.h \
./libstdc++-v3-4.8/include/bits/unique_ptr.h \
./libstdc++-v3-4.8/include/bits/uses_allocator.h \
./libstdc++-v3-4.8/include/bits/vector.tcc \
./libstdc++-v3-4.8/libsupc++/atomic_lockfree_defines.h \
./libstdc++-v3-4.8/libsupc++/cxxabi_forced.h \
./libstdc++-v3-4.8/libsupc++/exception_defines.h \
./libstdc++-v3-4.8/libsupc++/exception_ptr.h \
./libstdc++-v3-4.8/libsupc++/hash_bytes.h \
./libstdc++-v3-4.8/libsupc++/nested_exception.h \

DEBUG_SYMS=./libstdc++-v3-4.8/include/debug/debug.h \

EXT_SYMS=./libstdc++-v3-4.8/include/ext/alloc_traits.h \
./libstdc++-v3-4.8/include/ext/atomicity.h \
./libstdc++-v3-4.8/include/ext/bitmap_allocator.h \
./libstdc++-v3-4.8/include/ext/concurrence.h \
./libstdc++-v3-4.8/include/ext/new_allocator.h \
./libstdc++-v3-4.8/include/ext/numeric_traits.h \
./libstdc++-v3-4.8/include/ext/stdio_filebuf.h \
./libstdc++-v3-4.8/include/ext/stdio_sync_filebuf.h \
./libstdc++-v3-4.8/include/ext/string_conversions.h \
./libstdc++-v3-4.8/include/ext/type_traits.h \

INCLUDE_SYMS_TARGET=$(abspath $(INCLUDE_SYMS))
BACKWARD_SYMS_TARGET=$(abspath $(BACKWARD_SYMS))
BITS_SYMS_TARGET=$(abspath $(BITS_SYMS))
DEBUG_SYMS_TARGET=$(abspath $(DEBUG_SYMS))
EXT_SYMS_TARGET=$(abspath $(EXT_SYMS))
