C_OBJS=
ASM_OBJS=
COMPONENT=root_fprr.o
INTERFACES=sched schedinit
DEPENDENCIES=capmgr channel
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLCAPMGR) -lsl_thd_static_backend -lsl_mod_fprr 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
