/**
 * Copyright 2009 by Gabriel Parmer, gparmer@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text
	
cos_asm_server_stub_spdid(sched_comp_config_default)
cos_asm_server_stub_spdid(sched_comp_config)
cos_asm_server_stub_spdid(sched_comp_config_poststart)
cos_asm_server_stub_spdid(sched_comp_config_initstr)
