C_OBJS=micro_pong_lower.o
ASM_OBJS=
COMPONENT=micro_ppong_lower.o
INTERFACES=micro_pong_lower
DEPENDENCIES=cbuf_c sched printc mem_mgr_large valloc lock
IF_LIB=


include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
