# Booter disabled for the ppos branch currently

# C_OBJS=booter.o
# ASM_OBJS=
# COMPONENT=boot.o
# INTERFACES=cinfo failure_notif cgraph
# DEPENDENCIES=sched printc mem_mgr
# IF_LIB=
# ADDITIONAL_LIBS=-lcobj_format

# include ../../Makefile.subsubdir
# MANDITORY_LIB=simple_stklib.o
