# Customize this for your setup

TOP_DIR=/home/gparmer/research/composite/module/

TRANS_DIR=/home/gparmer/transfer
DEST_DIR=/root/experiments
KDIR=/home/gparmer/research/linux-2.6.22
TEST_DIR=/root/experiments/

LINKER_DIR=$(TOP_DIR)/user_prototype/linking/
NET_DIR=$(TOP_DIR)/net/

MAKE=make
CC=gcc
AR=ar
LD=ld
AS=$(CC)

