# Customize this for your setup

TRANS_DIR=/home/gparmer/transfer
DEST_DIR=/root/experiments
KDIR=/home/gparmer/research/linux-2.6.22
TEST_DIR=/root/experiments/

MAKE=make
CC=gcc
AR=ar
LD=ld
AS=$(CC)

