C_OBJS=sched_mgr.c
ASM_OBJS=
COMPONENT=fprr_sched.o
INTERFACES=schedmgr
DEPENDENCIES=resmgr
IF_LIB=
ADDITIONAL_LIBS=-lcos_kernel_api -lsl_sched -lcos_defkernel_api -lheap -lsl_mod_fprr -lsl_thd_static_backend -lsl_resmgr 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
