C_OBJS=https.o
ASM_OBJS=
COMPONENT=httpt.o
INTERFACES=http torrent
DEPENDENCIES=mem_mgr_large printc sched periodic_wake torrent cbuf_c evt lock valloc
FN_PREPEND=server_

include ../../Makefile.subsubdir

