C_OBJS=https.o
ASM_OBJS=
COMPONENT=httpt.o
INTERFACES=
DEPENDENCIES=mem_mgr_large printc sched periodic_wake torrent cbuf_c evt lock valloc
IF_LIB=../torlib.o
FN_PREPEND=server_

include ../../Makefile.subsubdir

