C_OBJS=init.o
ASM_OBJS=
COMPONENT=spin_comp.o
INTERFACES=
DEPENDENCIES=capmgr schedinit
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
