/**
 * Copyright 2007 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>
.text	

cos_asm_server_stub_spdid(lock_component_pretake)
cos_asm_server_stub_spdid(lock_component_take)
cos_asm_server_stub_spdid(lock_component_release)

cos_asm_server_stub_spdid(lock_component_alloc)
cos_asm_server_stub_spdid(lock_component_free)

cos_asm_server_stub_spdid(lock_stats)
cos_asm_server_stub_spdid(lock_stats_len)
