/**
 * Copyright 2013 by Qi Wang, interwq@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>

.text

cos_asm_server_stub_spdid(ainv_intra_create)
cos_asm_server_stub_spdid(ainv_intra_lookup)
cos_asm_server_stub_spdid(ainv_intra_lookup_ring)
cos_asm_server_stub_spdid(acap_srv_lookup_thd_num)

cos_asm_server_stub_spdid(acap_srv_lookup_intra)
cos_asm_server_stub_spdid(acap_srv_lookup_ring_intra)
cos_asm_server_stub_spdid(ainv_intra_wait_acap_create)
cos_asm_server_stub_spdid(ainv_intra_wakeup_acap_lookup)
