# We don't compile this code.  It is around only for
# historical/archival reasons.

.PHONY: all init cp clean
all:
	@echo "|     [--]   Skipping archives"

init:
	@echo "|     [--]   Skipping archives"

cp:
	@echo "|     [--]   Skipping archives"

clean:
	@echo "|     [--]   Skipping archives"
