C_OBJS=cap_mgr.c mem_mgr.c init.c
ASM_OBJS=
COMPONENT=capmgr.o
INTERFACES=capmgr
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcos_defkernel_api -lcos_kernel_api -lsl_raw -lsl_sched -lheap -lsl_mod_fprr -lsl_thd_static_backend

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
