/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>

.text	
cos_asm_server_stub_spdid(cbuf_c_create)
cos_asm_server_stub_spdid(cbuf_c_delete)
cos_asm_server_stub_spdid(cbuf_c_retrieve)
cos_asm_server_stub_spdid(cbuf_c_register)

cos_asm_server_stub(cbuf_set_concurrency)
cos_asm_server_stub(cbuf_spd_concurrency_estimate)
