C_OBJS=unit_capmgr_shmmap.c
ASM_OBJS=
COMPONENT=unitcapmgr_shmmap.o
INTERFACES=
DEPENDENCIES=capmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
