/**
 * Redistribution of this file is permitted under the BSD two clause license.
 *
 * Copyright 2019, The George Washington University
 * Author: Phani Gadepalli, phanikishoreg@gwu.edu
 */

#include <cos_asm_server_stub_simple_stack.h>

.text
cos_asm_server_stub(chan_out)
cos_asm_server_stub(chan_in)
//cos_asm_server_stub(chan_init)
//cos_asm_server_stub(chan_teardown)
//cos_asm_server_stub(chan_in_get)
//cos_asm_server_stub(chan_out_get)
//cos_asm_server_stub(chan_send)
//cos_asm_server_stub(chan_recv)
//cos_asm_server_stub(chan_async_send)
//cos_asm_server_stub(chan_async_recv)
