COMPONENT=unit_schedcomp_test.o
INTERFACES=
DEPENDENCIES=capmgr
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLCAPMGR) -lsl_thd_static_backend -lsl_mod_rr -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
