#ifndef COS_GOMP_H
#define COS_GOMP_H

#include <part.h>

#define COS_GOMP_MAX_THDS PART_MAX_PAR_THDS 
#define COS_GOMP_CORE_MAX_THDS PART_MAX_CORE_THDS
#define COS_GOMP_MAX_CHILD PART_MAX_CHILD
#define COS_GOMP_MAX_TASKS PART_MAX_TASKS 

#endif /* COS_GOMP_H */
