C_OBJS=replica.o
ASM_OBJS=
COMPONENT=test_replica.o
INTERFACES=
DEPENDENCIES=voter
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
