C_OBJS=unit_capmgr.c
ASM_OBJS=
COMPONENT=unitcapmgr.o
INTERFACES=
DEPENDENCIES=capmgr channel
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBCOSDEFKERN) 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
