COMPONENT=llbooter_1.o
ASM_OBJS=s_stub_1.o
COMPONENT=llboot_comp_1.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api -llibekf

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
