#ifndef CFE_SENSOREMU_H
#define CFE_SENSOREMU_H

#define SENSOREMU_Q_NAME "SENSOR_EMU_QUEUE"
#define SENSOREMU_INT_US (500*1000) //500ms
#define SENSOREMU_RETRY_US (10000)
#define SENSOREMU_Q_DEPTH 20
#define SENSOREMU_DATASZ 512

#define SENSOREMU_USE_HPET

#endif /* CFE_SENSOREMU_H */
