C_OBJS=cFE_stub.o
ASM_OBJS=
COMPONENT=cFE_booter.o
INTERFACES=
DEPENDENCIES=
IF_LIB=./composite_cFE.o
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
