C_OBJS=exe_cbuf_periodic.o
ASM_OBJS=
COMPONENT=exe_cb_pt.o
INTERFACES=
DEPENDENCIES=periodic_wake sched printc cbuf_mgr valloc exe_cbuf_synth_hier timed_blk
IF_LIB=

include ../../Makefile.subsubdir

