C_OBJS=exe_cbuf_periodic.o
ASM_OBJS=
COMPONENT=exe_cb_pt.o
INTERFACES=
DEPENDENCIES=periodic_wake sched printc cbufp cbuf_c valloc mem_mgr_large exe_cbuf_synth_hier timed_blk
IF_LIB=

include ../../Makefile.subsubdir

