C_OBJS=pong_lower.o
ASM_OBJS=
COMPONENT=ppong_lower.o
INTERFACES=pong_lower
DEPENDENCIES=cbuf_c sched printc lock mem_mgr_large valloc
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
