IF_NAME=
C_OBJS=vcos_kernel_api.o micro_booter.o vkernel_init.o
#C_OBJS=micro_booter.o vkernel_init.o
ASM_OBJS=cos_asm_scheduler.o testinv.o
COMPONENT=vkernel_boot.o
DEPENDENCIES=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
