COMPONENT=unit_schedaep_test.o
INTERFACES=
DEPENDENCIES=sched capmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api #required for cos_sinv in llboot.h!

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
