C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=stconnmt.o
INTERFACES=lateness_report
DEPENDENCIES=torrent printc mem_mgr_large sched valloc cbufp evt net_transport lock
IF_LIB=
FN_PREPEND=from_

include ../../Makefile.subsubdir

