C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=stconn.o
INTERFACES=
DEPENDENCIES=torrent printc mem_mgr_large sched valloc cbufp cbuf_c evt net_transport lock
IF_LIB=
FN_PREPEND=from_

include ../../Makefile.subsubdir

