/**
 * Copyright 2009 by Boston University.
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 *
 * Author: Gabriel Parmer, gabep1@cs.bu.edu
 */

#include <cos_asm_server_stub.h>

cos_asm_server_stub_spdid(netif_event_create)
cos_asm_server_stub_spdid(netif_event_release)
cos_asm_server_stub_spdid(netif_event_wait)
cos_asm_server_stub_spdid(netif_event_xmit)

cos_asm_server_stub(netif_upcall_cyc)
