COMPONENT=part_test.o
INTERFACES=
#DEPENDENCIES=capmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api $(LIBSLRAW) -lsl_mod_part_fifo -lsl_thd_static_backend -lsl_lock -lcos_defkernel_api -lpart_raw -lsl_blkpt -lps

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
