C_OBJS=unit_resmgr_shmmap.c
ASM_OBJS=
COMPONENT=unitresmgr_shmmap.o
INTERFACES=
DEPENDENCIES=resmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
