C_OBJS=../*.c
COMPONENT=cnic.o
INTERFACES=rk
DEPENDENCIES=capmgr schedinit
IF_LIB=
ADDITIONAL_LIBS=-lcos_defkernel_api -lcos_kernel_api -lsl_capmgr -lsl_lock -lsl_sched -lsl_mod_fprr -lsl_thd_static_backend -lheap

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
