C_OBJS=../*.c
COMPONENT=cnic.o
INTERFACES=rk
DEPENDENCIES=shdmem
IF_LIB=
ADDITIONAL_LIBS=-lcos_defkernel_api -lcos_kernel_api -lsl -lsl_mod_fprr -lsl_thd_static_backend -lheap

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
