C_OBJS=../*.c
COMPONENT=cnic.o
INTERFACES=rk
DEPENDENCIES=capmgr schedinit
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLCAPMGR) -lsl_mod_fp -lsl_thd_static_backend -lheap

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
