C_OBJS=micro_xcores.o test_ipi_n_n.o test_ipi_interference.o test_ipi_switch.o test_ipi_roundtrip.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=micro_xcore.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_ubench

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
