C_OBJS=micro_booter.o vkernel.o
ASM_OBJS=cos_asm_scheduler.o inv.o
COMPONENT=vkernel_boot.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
