/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text
cos_asm_server_stub(side)
cos_asm_server_stub(up)
cos_asm_server_stub(diagonal)
cos_asm_server_stub(determine_steps)
cos_asm_server_stub(send_task)
cos_asm_server_stub(get_loc)
cos_asm_server_stub(receive_task)
