C_OBJS=micro_pong.o
ASM_OBJS=
COMPONENT=micro_ppong.o
INTERFACES=micro_pong
DEPENDENCIES=sched printc cbuf_mgr valloc mem_mgr_large lock
IF_LIB=

include ../../Makefile.subsubdir
#MANDITORY_LIB=simple_stklib.o
