COMPONENT=rk_api_stubcomp.o
ASM_OBJS=
COMPONENT=rk_stubcomp.o
INTERFACES=
DEPENDENCIES=capmgr channel sched schedinit rk 
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api -lsinv_server

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
