C_OBJS=
ASM_OBJS=
COMPONENT=test_sched.o
INTERFACES=sched schedinit crt
DEPENDENCIES=capmgr channel
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLCAPMGR) -lsl_thd_static_backend -lsl_mod_fprr -lsl_blkpt

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
