COMPONENT=srvdummy_stub.o
ASM_OBJS=
COMPONENT=srvdummy_stubcomp.o
INTERFACES=
DEPENDENCIES=capmgr channel sched schedinit srv_dummy
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api -lsinv_server

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
