C_OBJS=https.o
ASM_OBJS=
COMPONENT=httpt.o
INTERFACES=torrent
DEPENDENCIES=mem_mgr_large printc sched periodic_wake torrent cbufp cbuf_c evt lock valloc
FN_PREPEND=server_

include ../../Makefile.subsubdir

