/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub_3rets(call_intern)
cos_asm_server_stub_3rets(call_two_intern)
cos_asm_server_stub_3rets(call_three_intern)
cos_asm_server_stub_3rets(call_four_intern)

cos_asm_server_stub_3rets(call_arg_intern)
cos_asm_server_stub_3rets(call_args_intern)

cos_asm_server_stub_3rets(call_3rets)
