C_OBJS=ppos_booter.o
ASM_OBJS=inv.o
COMPONENT=ppos_boot.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
