#C_OBJS=unit_schedlib.o
COMPONENT=unit_sl.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcos_defkernel_api -lcos_kernel_api -lheap

include ../../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
