C_OBJS=booter.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=llboot.o
INTERFACES=cgraph pgfault sched_hier upcall qfault
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
