C_OBJS=tmem_policy.o
ASM_OBJS=
COMPONENT=tp.o
INTERFACES=
DEPENDENCIES=periodic_wake sched printc stkmgr cbuf_c timed_blk valloc mem_mgr_large mem_pool exe_cbuf_synth_hier
IF_LIB=

include ../../Makefile.subsubdir

