COMPONENT=unit_slrcvtest.o
INTERFACES=
DEPENDENCIES=capmgr schedinit work
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLCAPMGR) -lsl_mod_fprr -lsl_thd_static_backend -lcos_dcb -lsl_blkpt

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
