COMPONENT=unit_slrcvtest.o
INTERFACES=
DEPENDENCIES=capmgr schedinit
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLCAPMGR) -lsl_mod_rr -lsl_thd_static_backend -lcos_dcb

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
