/**
 * Copyright 2012 by Gabriel Parmer, gparmer@gwu.edu.
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text	
cos_asm_server_stub_spdid(cbuf_create)
cos_asm_server_stub_spdid(cbufp_delete)
cos_asm_server_stub_spdid(cbufp_retrieve)
cos_asm_server_stub_spdid(cbufp_register)
cos_asm_server_stub_spdid(cbufp_map_at)
cos_asm_server_stub_spdid(cbufp_unmap_at)
cos_asm_server_stub_spdid(cbufp_map_collect)
cos_asm_server_stub_spdid(cbufp_collect)
