C_OBJS=exe_cbuf_synth_hier.o
ASM_OBJS=
COMPONENT=exe_cb_sh.o
INTERFACES=exe_cbuf_synth_hier
DEPENDENCIES=cbuf_mgr sched printc valloc lock exe_self_suspension timed_blk synth_hier
FN_PREPEND=calll_ callr_

include ../../Makefile.subsubdir

