C_OBJS=exe_cbuf_synth_hier.o
ASM_OBJS=
COMPONENT=exe_cb_sh.o
INTERFACES=exe_cbuf_synth_hier
DEPENDENCIES=cbuf_c sched sched_conf printc mem_mgr_large valloc lock exe_self_suspension timed_blk
IF_LIB=

include ../../Makefile.subsubdir

