C_OBJS=mbox_server.o
ASM_OBJS=
COMPONENT=micro_mbox_server.o
INTERFACES=
DEPENDENCIES=periodic_wake printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock
IF_LIB=

include ../../Makefile.subsubdir
