C_OBJS=malloc_comp.o
ASM_OBJS=
COMPONENT=malloccomp.o
INTERFACES=test_malloc_comp
DEPENDENCIES=cbuf_mgr printc sched lock valloc # all of these??? Probably not
IF_LIB=

include ../../Makefile.subsubdir
