C_OBJS=micro_pong.o
ASM_OBJS=
COMPONENT=micro_ppong.o
INTERFACES=micro_pong
DEPENDENCIES=cbuf_c sched printc lock mem_mgr_large valloc micro_pong_lower
IF_LIB=

include ../../Makefile.subsubdir
#MANDITORY_LIB=simple_stklib.o
