C_OBJS=unit_resmgr.c
ASM_OBJS=
COMPONENT=2_0_unitresmgr.o
INTERFACES=
DEPENDENCIES=resmgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api -lsl_rawmgr

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
