COMPONENT=par_test_comp.o
INTERFACES=
DEPENDENCIES=sched workgen
IF_LIB=
ADDITIONAL_LIBS=-lcos_kernel_api #required for cos_sinv in llboot.h!

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
