C_OBJS=ping_two.o
ASM_OBJS=
COMPONENT=_0_pingp_two.o
INTERFACES=
DEPENDENCIES=pong_two
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
