C_OBJS=car_mgr.o
ASM_OBJS=
COMPONENT=car_mgr1.o
INTERFACES=
DEPENDENCIES=capmgr sched robot_cont
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
