C_OBJS=car_mgr.o
ASM_OBJS=
COMPONENT=car_mgr1.o
INTERFACES=
#DEPENDENCIES=robot_sched camera
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
