/**
 * Copyright 2009 by Boston University.
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 *
 * Author: Gabriel Parmer, gabep1@cs.bu.edu
 */

#include <cos_asm_server_stub.h>
	
.text
cos_asm_server_stub_spdid(content_create)
cos_asm_server_stub_spdid(content_split)
cos_asm_server_stub_spdid(content_remove)
cos_asm_server_stub_spdid(content_write)
cos_asm_server_stub_spdid(content_read)
cos_asm_server_stub_spdid(async_open)
cos_asm_server_stub_spdid(async_close)
cos_asm_server_stub_spdid(async_request)
cos_asm_server_stub_spdid(async_retrieve)
