/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>
	
.text
cos_asm_server_stub(cos_app_open)
cos_asm_server_stub(cos_socket)
cos_asm_server_stub(cos_listen)
cos_asm_server_stub(cos_bind)
cos_asm_server_stub(cos_accept)
cos_asm_server_stub(cos_close)
cos_asm_server_stub(cos_split)
cos_asm_server_stub(cos_write)
cos_asm_server_stub(cos_read)
cos_asm_server_stub(cos_wait)
cos_asm_server_stub(cos_wait_all)	
