C_OBJS=pong.o
ASM_OBJS=
COMPONENT=ppong.o
INTERFACES=pong
DEPENDENCIES=cbuf_c sched printc lock mem_mgr_large valloc pong_lower
IF_LIB=

include ../../Makefile.subsubdir
#MANDITORY_LIB=simple_stklib.o
