/**
 * Copyright 2007 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>
.text	

cos_asm_server_stub_spdid(jpeg_CreateDecompress)
cos_asm_server_stub_spdid(jpeg_destroy_decompress)
cos_asm_server_stub_spdid(jpeg_finish_decompress)
cos_asm_server_stub_spdid(jpeg_read_header)
cos_asm_server_stub_spdid(jpeg_read_scanlines)
cos_asm_server_stub_spdid(jpeg_start_decompress)
cos_asm_server_stub_spdid(jpeg_std_error)
cos_asm_server_stub_spdid(jpeg_stdio_src)
