C_OBJS=rk_kypercall.c, rk_inv_api.c, rk_sched.c, rk_stubs.c, rump_booter.c, rumpcalls.c, rump_cos_alloc.c
ASM_OBJS=inv.o, start.o
COMPONENT=rk.o
INTERFACES=rk
DEPENDENCIES=shdmem

include ../Makefile.subdir

MANDITORY_LIB=simple_stklib.o
