/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#define __ASM__
#include <consts.h>
#include <cos_asm_server_stub_simple_stack.h>

.text
cos_asm_server_stub(cos_sinv)
cos_asm_server_stub(rk_sendto)
cos_asm_server_stub(rk_recvfrom)
cos_asm_server_stub(rk_socket)
cos_asm_server_stub(rk_connect)
cos_asm_server_stub(rk_bind)
cos_asm_server_stub(rk_mmap)
cos_asm_server_stub(rk_setsockopt)
cos_asm_server_stub(rk_getsockopt)
cos_asm_server_stub(rk_write)
cos_asm_server_stub(rk_writev)
cos_asm_server_stub(rk_read)
cos_asm_server_stub(rk_select)
cos_asm_server_stub(rk_listen)
cos_asm_server_stub(rk_accept)
cos_asm_server_stub(rk_open)
cos_asm_server_stub(rk_close)
cos_asm_server_stub(rk_fcntl)
cos_asm_server_stub(rk_unlink)
cos_asm_server_stub(rk_ftruncate)
cos_asm_server_stub(rk_getsockname)
cos_asm_server_stub(rk_getpeername)
cos_asm_server_stub(rk_clock_gettime)
cos_asm_server_stub(get_boot_done)
cos_asm_server_stub(test_fs)
cos_asm_server_stub(test_entry)
cos_asm_server_stub(rk_init)
