/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub(cos_sinv)
cos_asm_server_stub(cos_spdid_get)
cos_asm_server_stub(rk_socketcall_init)
cos_asm_server_stub(rk_entry)
cos_asm_server_stub(rk_sendto)
cos_asm_server_stub(rk_recvfrom)
cos_asm_server_stub(rk_socket)
cos_asm_server_stub(get_boot_done)
cos_asm_server_stub(test_shdmem)
cos_asm_server_stub(test_fs)
cos_asm_server_stub(test_entry)
