ASM_OBJS=cos_asm_scheduler.o inv.o start.o
COMPONENT=rump_boot.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
