C_OBJS=micro_booter.o rumpcalls.o rump_cos_alloc.o cos_init.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=rump_boot.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
