C_OBJS=
ASM_OBJS=
COMPONENT=hier_fprr.o
INTERFACES=sched schedinit
DEPENDENCIES=capmgr sched schedinit
IF_LIB=
FN_PREPEND=parent_
ADDITIONAL_LIBS=-lcos_kernel_api -lsl_sched -lcos_defkernel_api -lheap -lsl_mod_fprr -lsl_thd_static_backend -lsl_capmgr 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
