C_OBJS=cos_net.o
ASM_OBJS=
COMPONENT=net.o
INTERFACES=net_transport
DEPENDENCIES=sched mem_mgr_large printc lock timed_blk evt net_internet net_portns valloc
IF_LIB=../net_stack.o

include ../../Makefile.subsubdir

