C_OBJS=tlsmanager.o
ASM_OBJS=
COMPONENT=tlsmgr.o
INTERFACES=tlsmgr
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS= -lcos_kernel_api -lcos_defkernel_api
OBJLIBS+=$(POSIX_LIB)

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
