C_OBJS=unit_srvdummy.c
ASM_OBJS=
COMPONENT=unitsrvdummy.o
INTERFACES=
DEPENDENCIES=sched schedinit srv_dummy
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBCOSDEFKERN) 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
