/**
 * Copyright 2009 by Boston University.
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 *
 * Author: Gabriel Parmer, gabep1@cs.bu.edu, 2009
 */

#include <cos_asm_server_stub.h>

cos_asm_server_stub_spdid(net_create_tcp_connection)
cos_asm_server_stub_spdid(net_create_udp_connection)
cos_asm_server_stub_spdid(net_accept)
cos_asm_server_stub_spdid(net_accept_data)
cos_asm_server_stub_spdid(net_listen)
cos_asm_server_stub_spdid(net_bind)
cos_asm_server_stub_spdid(net_connect)
cos_asm_server_stub_spdid(net_close)

cos_asm_server_stub_spdid(net_send)
cos_asm_server_stub_spdid(net_recv)
