C_OBJS=micro_cbuf3.o
ASM_OBJS=
COMPONENT=micbuf3.o
INTERFACES=micro_cbuf3
DEPENDENCIES=sched printc cbuf_mgr valloc lock
IF_LIB=

include ../../Makefile.subsubdir
##using simple_stk when measure cbuf with PIP
##MANDITORY_LIB=simple_stklib.o
