COMPONENT=llbooter.o
COMPONENT=llboot_comp.o
INTERFACES=init addr
DEPENDENCIES=init
IF_LIB=
ADDITIONAL_LIBS=-lcos_kernel_api -lcos_defkernel_api -linitargs -lcrt

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
