COMPONENT=llbooter.o
COMPONENT=llboot_comp.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api -lcos_defkernel_api -linitargs

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
