C_OBJS=mbox_client.o
ASM_OBJS=
COMPONENT=micro_mbox_client.o
INTERFACES=
DEPENDENCIES=periodic_wake printc torrent sched cbuf_mgr evt mem_mgr_large valloc lock
IF_LIB=

include ../../Makefile.subsubdir
