/**
 * Copyright 2009 by Gabriel Parmer, gparmer@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>
//#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub(nwrite)
cos_asm_server_stub(nread)
cos_asm_server_stub(replica_confirm)
cos_asm_server_stub(get_read_buf)
cos_asm_server_stub(get_write_buf)
cos_asm_server_stub(confirm_fork)
