/**
 * Copyright 2009 by Gabriel Parmer, gabep1@cs.bu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>
//#include <cos_asm_server_stub_simple_stack.h>

.text

cos_asm_server_stub(call)
cos_asm_server_stub(call_cs)
cos_asm_server_stub(call_buf2buf)
cos_asm_server_stub(simple_call_buf2buf)
cos_asm_server_stub(call_cbufp2buf)
