INTERFACES=capmgr capmgr_create init
DEPENDENCIES=init addr
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLRAW) -lsl_mod_fprr -lsl_thd_static_backend -linitargs -lcrt

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
