COMPONENT=micro_schedovhdtest.o
INTERFACES=
DEPENDENCIES=capmgr sched schedinit
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLCAPMGR) -lsl_mod_fprr -lsl_thd_static_backend

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
