/**
 * Copyright 2011 by Gabriel Parmer, gparmer@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>
.text	
cos_asm_server_fn_stub_spdid(tsplit, __sg_tsplit)
cos_asm_server_fn_stub_spdid(tmerge, __sg_tmerge)
cos_asm_server_stub_spdid(trelease)
cos_asm_server_stub_spdid(tread)
cos_asm_server_stub_spdid(twrite)
cos_asm_server_fn_stub_spdid(treadp, __sg_treadp)
cos_asm_server_stub_spdid(twritep)
cos_asm_server_fn_stub_spdid(trmeta, __sg_trmeta)
cos_asm_server_fn_stub_spdid(twmeta, __sg_twmeta)
