include ../../../../../Makefile.src

INCLUDE = 
#-I$(SHAREDINC) -I$(CDIR)/include/
CFILES  = $(wildcard *.c)
OFILES  = $(CFILES:%.c=%.o)
EXEC    = $(CFILES:%.c=%)
OPT     = -ggdb3
CFLAGS  = -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -fno-stack-protector -fno-omit-frame-pointer $(OPT) $(INCLUDE) 

$(EXEC):$(OFILES)
	$(CC) -o $@ $<

%.o:%.c
	$(CC) $(CFLAGS) -c -o $(@) $<

cp: 
	cp $(EXEC) $(TRANS_DIR)
clean:
	rm -f $(OFILES) $(EXEC)
