C_OBJS=micro_cbuf2.o
ASM_OBJS=
COMPONENT=micbuf2.o
INTERFACES=micro_cbuf2
DEPENDENCIES=micro_cbuf3 lock sched printc valloc mem_mgr_large
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
