C_OBJS=booter.o quarantine.o
ASM_OBJS=
COMPONENT=cbboot.o
INTERFACES=failure_notif cgraph quarantine qfault lock
DEPENDENCIES=sched printc mem_mgr cinfo cbuf_mgr upcall lock
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
