C_OBJS=unit_defcompinfo.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=unit_defci.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_defkernel_api -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
