# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"

    config.vm.provider "virtualbox" do |v|
        v.name = "composite_dev"
        v.memory = 3072
        v.cpus = 2
        v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end

    # Disable the default syncing
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Instead sync the actual composite folder
    config.vm.synced_folder "../", "/home/vagrant/composite"
    config.vm.synced_folder "../../lib_composite", "/home/vagrant/lib_composite"

    config.vm.provision :shell,path: "provision.sh"
end
