C_OBJS=cxx.o
COMPONENT=cxx_test.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
OBJLIBS += $(POSIX_LIB)
ADDITIONAL_LIBS=-lheap -lcobj_format -lcos_kernel_api -lcos_defkernel_api -lstdc++ -lsupc++ -lsl -lsl_mod_fprr -lsl_thd_static_backend

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
