C_OBJS=cxx.o
COMPONENT=cxx_test.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lstdc++ -lsupc++ -lcobj_format -lcos_defkernel_api -lcos_kernel_api -lsl_raw -lsl_sched -lheap -lsl_thd_static_backend -lsl_lock -lsl_mod_fprr
OBJLIBS+=$(POSIX_LIB)

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
