C_OBJS=cxx.o
COMPONENT=cxx_test.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
OBJLIBS += $(POSIX_LIB)
ADDITIONAL_LIBS=-lstdc++ -lsupc++ -lcobj_format $(LIBSLRAW) -lsl_thd_static_backend -lsl_lock -lsl_mod_fprr

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
