/**
 * Copyright 2013 by Qi Wang, interwq@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */

#include <cos_asm_server_stub.h>

.text

cos_asm_server_stub_spdid(acap_srv_fn_mapping)
cos_asm_server_stub_spdid(acap_srv_ncaps)
cos_asm_server_stub_spdid(acap_cli_lookup)
cos_asm_server_stub_spdid(acap_cli_lookup_ring)

cos_asm_server_stub_spdid(acap_srv_lookup)
cos_asm_server_stub_spdid(acap_srv_lookup_ring)
