/**
 * Copyright 2009 by Andrew Sweeney, ajs86@gwu.edu
 *
 * Redistribution of this file is permitted under the GNU General
 * Public License v2.
 */


#include <cos_asm_server_stub_simple_stack.h>

.text

/*cos_asm_server_stub_spdid(stkmgr_get_stack)*/
cos_asm_server_stub_spdid(stkmgr_grant_stack)
cos_asm_server_stub_spdid(stkmgr_return_stack)
cos_asm_server_stub(stkmgr_hello_world)
cos_asm_server_stub(stkmgr_got_from_list)
