include Makefile.cosconfig

# the directory this file is in
TOP_DIR=$(CODE_DIR)
# the directory all objects will be copied to when they are ready for
# deployment
#TRANS_DIR=$(HOME_DIR)/transfer

KDIR=$(TOP_DIR)/kernel/
KINC=$(TOP_DIR)/kernel/include/
SHAREDINC=$(TOP_DIR)/kernel/include/shared/
CDIR=$(TOP_DIR)/components/

# tools
MAKE=make
CC=gcc
AR=ar
LD=ld
AS=$(CC)
MV=mv
CP=cp
RM=rm
