COMPONENT=crtt.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLRAW) -lsl_mod_fprr -lsl_thd_static_backend -lsl_blkpt

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
