C_OBJS=stkmgr.o
ASM_OBJS=
COMPONENT=sm.o
INTERFACES=stkmgr
DEPENDENCIES=sched printc lock mem_mgr_large valloc cinfo mem_pool
IF_LIB=../complib.o

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
