/**
 * Redistribution of this file is permitted under the BSD two clause license.
 *
 * Copyright 2018, The George Washington University
 * Author: Phani Gadepalli, phanikishoreg@gwu.edu
 */

#define __ASM__
#include <consts.h>
#include <cos_asm_server_stub_simple_stack.h>

.text
cos_asm_server_stub_rets(channel_shared_page_allocn_cserialized)
cos_asm_server_stub_rets(channel_shared_page_map_cserialized)
