C_OBJS=init.c sched_mgr.c
ASM_OBJS=
COMPONENT=fprr_rawsched.o
INTERFACES=schedmgr
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcos_kernel_api -lsl_sched -lcos_defkernel_api -lheap -lsl_mod_fprr -lsl_thd_static_backend -lsl_raw 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
