C_OBJS=booter.o
ASM_OBJS=cos_asm_scheduler.o
COMPONENT=llboot.o
INTERFACES=failure_notif cgraph
DEPENDENCIES=printc
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
