C_OBJS=fd.o
ASM_OBJS=
COMPONENT=face_detect.o
INTERFACES=
DEPENDENCIES=sched printc timed_blk torrent evt cbuf_mgr valloc lock
IF_LIB=./cos_libccv.a
OBJLIBS += $(POSIX_LIB)

cp:
clean:

# pre: first all
# first:
# 	$(info |     [CP]   copying cos_libccv.a from libccv)
# 	@cp $(CCVOBJ) .

# include ../../Makefile.subsubdir
