C_OBJS=parbench.o
ASM_OBJS=
COMPONENT=par_bench.o
INTERFACES=
DEPENDENCIES=par_mgr mem_mgr_large sched valloc printc lock timed_blk acap_pong
IF_LIB=
ADDITIONAL_LIBS=-lheap

include ../../Makefile.subsubdir

CFLAGS += -fopenmp

