COMPONENT=unit_slxcoretests.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLRAW) -lsl_mod_rr -lsl_thd_static_backend -lcos_dcb

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
