C_OBJS=unit_srvdummy_acom.c
ASM_OBJS=
COMPONENT=unitsrvdummyacom.o
INTERFACES=
DEPENDENCIES=channel capmgr sched schedinit
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBCOSDEFKERN) -lacom_client 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
