C_OBJS=booter.o
ASM_OBJS=
COMPONENT=cbboot.o
INTERFACES=failure_notif cgraph
DEPENDENCIES=sched printc mem_mgr cinfo cbuf_mgr
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
