C_OBJS=
ASM_OBJS=
COMPONENT=root_fprr_raw.o
INTERFACES=sched schedinit
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=$(LIBSLRAW) -lsl_thd_static_backend -lsl_mod_fprr

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
