C_OBJS=
ASM_OBJS=
COMPONENT=root_fprr_raw.o
INTERFACES=sched schedinit
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcos_kernel_api -lsl_sched -lcos_defkernel_api -lheap -lsl_mod_fprr -lsl_thd_static_backend -lsl_raw 

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
